name: example
description: "A new Flutter project."
publish_to: 'none'
version: 1.1.1+8

environment:
  sdk: '>=3.4.3 <4.0.0'
dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
flutter:
  uses-material-design: true