name: releascribe_cli
description: Effortlessly manage software releases with advanced command-line interface.
version: 0.1.0
homepage: https://github.com/lsaudon/releascribe_cli
repository: https://github.com/lsaudon/releascribe_cli
issue_tracker: https://github.com/lsaudon/releascribe_cli/issues

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.5.0
  cli_completion: ^0.5.0
  file: ^7.0.0
  mason_logger: ^0.2.15
  process: ^5.0.2
  pub_semver: ^2.1.4
  pub_updater: ^0.4.0
  pubspec_parse: ^1.3.0
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.4.11
  build_verify: ^3.1.0
  build_version: ^2.1.1
  mocktail: ^1.0.4
  test: ^1.25.8

executables:
  releascribe_cli:
