name: Create Tag on PR Merge

on:
  pull_request:
    types: [closed]

jobs:
  create-tag:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.title, 'releascribe-')
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the repository
      uses: actions/checkout@v4
    - name: Create a new tag
      run: |
        TAG_NAME=${{ github.event.pull_request.title }}
        echo $TAG_NAME
