name: releascribe_cli

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/**"
      - "lib/**"
      - "test/**"
      - "pubspec.yaml"

jobs:

  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/dart_package.yml@v1
    with:
      no_example: true
      min_coverage: 97

  verify-version:
    runs-on: ubuntu-latest
    steps:
      - name: 📚 Git Checkout
        uses: actions/checkout@v4

      - name: 🎯 Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: "stable"

      - name: 📦 Install Dependencies
        run: dart pub get --no-example

      - name: 🔎 Verify version
        run: dart run test --run-skipped -t version-verify
